name: Android Build Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Setup Environment and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run Kotlin Linter
        run: ./gradlew ktlintCheck

      - name: Run PMD
        run: ./gradlew pmd

      - name: Run Checkstyle
        run: ./gradlew checkstyle

      - name: Compile code
        run: ./gradlew assembleDebug